### ISSUE TITLE
ValueError in conversion

### ISSUE THREAD

**Issue by aannabe** [QuantumPackage/qmcpack#5]
Hi, I am seeing a ValueError in a molecule with ecp.
QP2QMCACK.h5 is still generated but I don't know if I should be worried above this message.
My files are attached. Thank you.

```
Traceback (most recent call last):
  File "/home/gani/codes/qp2/src/qmcpack/qp_convert_qmcpack_to_ezfio.py", line 604, in <module>
    groupMultiDet.create_dataset("Coeff",(len(psi_coef_small),),dtype="f8",data=psi_coef)
  File "/home/gani/anaconda3/envs/nexus2/lib/python2.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/gani/anaconda3/envs/nexus2/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 95, in make_new_dset
    raise ValueError("Shape tuple is incompatible with data")
ValueError: Shape tuple is incompatible with data

```
[debug_dz.tar.gz](https://github.com/QuantumPackage/qmcpack/files/4814685/debug_dz.tar.gz)

**Comment by TApplencourt** [comment]
Thank you for the bug report (and the reproducer:)).

It should work now! Please let us know if you have more question / concern.

Thanks again!
